# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import neural_network_pb2 as neural__network__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in neural_network_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NeuralNetworkServiceStub(object):
    """Neural Network Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/neural_network.NeuralNetworkService/Initialize',
                request_serializer=neural__network__pb2.InitializeRequest.SerializeToString,
                response_deserializer=neural__network__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Forward = channel.unary_unary(
                '/neural_network.NeuralNetworkService/Forward',
                request_serializer=neural__network__pb2.ForwardRequest.SerializeToString,
                response_deserializer=neural__network__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.Backward = channel.unary_unary(
                '/neural_network.NeuralNetworkService/Backward',
                request_serializer=neural__network__pb2.BackwardRequest.SerializeToString,
                response_deserializer=neural__network__pb2.BackwardResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/neural_network.NeuralNetworkService/Update',
                request_serializer=neural__network__pb2.UpdateRequest.SerializeToString,
                response_deserializer=neural__network__pb2.UpdateResponse.FromString,
                _registered_method=True)


class NeuralNetworkServiceServicer(object):
    """Neural Network Service definition
    """

    def Initialize(self, request, context):
        """Initialize the device with layer configurations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forward(self, request, context):
        """Forward pass through the layers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Backward(self, request, context):
        """Backward pass for gradient computation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Update parameters using computed gradients
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NeuralNetworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=neural__network__pb2.InitializeRequest.FromString,
                    response_serializer=neural__network__pb2.InitializeResponse.SerializeToString,
            ),
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=neural__network__pb2.ForwardRequest.FromString,
                    response_serializer=neural__network__pb2.ForwardResponse.SerializeToString,
            ),
            'Backward': grpc.unary_unary_rpc_method_handler(
                    servicer.Backward,
                    request_deserializer=neural__network__pb2.BackwardRequest.FromString,
                    response_serializer=neural__network__pb2.BackwardResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=neural__network__pb2.UpdateRequest.FromString,
                    response_serializer=neural__network__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neural_network.NeuralNetworkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neural_network.NeuralNetworkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NeuralNetworkService(object):
    """Neural Network Service definition
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_network.NeuralNetworkService/Initialize',
            neural__network__pb2.InitializeRequest.SerializeToString,
            neural__network__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_network.NeuralNetworkService/Forward',
            neural__network__pb2.ForwardRequest.SerializeToString,
            neural__network__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Backward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_network.NeuralNetworkService/Backward',
            neural__network__pb2.BackwardRequest.SerializeToString,
            neural__network__pb2.BackwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_network.NeuralNetworkService/Update',
            neural__network__pb2.UpdateRequest.SerializeToString,
            neural__network__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
