# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import pokemon_pb2 as pokemon__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pokemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PokemonServiceStub(object):
    """Service definition for Trainer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitDevice = channel.unary_unary(
                '/pokemon.PokemonService/InitDevice',
                request_serializer=pokemon__pb2.InitDeviceRequest.SerializeToString,
                response_deserializer=pokemon__pb2.InitDeviceResponse.FromString,
                _registered_method=True)
        self.StartTraining = channel.unary_unary(
                '/pokemon.PokemonService/StartTraining',
                request_serializer=pokemon__pb2.StartTrainingRequest.SerializeToString,
                response_deserializer=pokemon__pb2.StartTrainingResponse.FromString,
                _registered_method=True)


class PokemonServiceServicer(object):
    """Service definition for Trainer
    """

    def InitDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokemonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.InitDevice,
                    request_deserializer=pokemon__pb2.InitDeviceRequest.FromString,
                    response_serializer=pokemon__pb2.InitDeviceResponse.SerializeToString,
            ),
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=pokemon__pb2.StartTrainingRequest.FromString,
                    response_serializer=pokemon__pb2.StartTrainingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pokemon.PokemonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pokemon.PokemonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PokemonService(object):
    """Service definition for Trainer
    """

    @staticmethod
    def InitDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pokemon.PokemonService/InitDevice',
            pokemon__pb2.InitDeviceRequest.SerializeToString,
            pokemon__pb2.InitDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pokemon.PokemonService/StartTraining',
            pokemon__pb2.StartTrainingRequest.SerializeToString,
            pokemon__pb2.StartTrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
