# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import trainer_pb2 as trainer__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trainer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainerServiceStub(object):
    """Service definition for Trainer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPokemon = channel.unary_unary(
                '/trainer.TrainerService/RegisterPokemon',
                request_serializer=trainer__pb2.RegisterPokemonRequest.SerializeToString,
                response_deserializer=trainer__pb2.RegisterPokemonResponse.FromString,
                _registered_method=True)
        self.Training = channel.unary_unary(
                '/trainer.TrainerService/Training',
                request_serializer=trainer__pb2.TrainingResults.SerializeToString,
                response_deserializer=trainer__pb2.TrainingResultsResponse.FromString,
                _registered_method=True)


class TrainerServiceServicer(object):
    """Service definition for Trainer
    """

    def RegisterPokemon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Training(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPokemon': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPokemon,
                    request_deserializer=trainer__pb2.RegisterPokemonRequest.FromString,
                    response_serializer=trainer__pb2.RegisterPokemonResponse.SerializeToString,
            ),
            'Training': grpc.unary_unary_rpc_method_handler(
                    servicer.Training,
                    request_deserializer=trainer__pb2.TrainingResults.FromString,
                    response_serializer=trainer__pb2.TrainingResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trainer.TrainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trainer.TrainerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainerService(object):
    """Service definition for Trainer
    """

    @staticmethod
    def RegisterPokemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.TrainerService/RegisterPokemon',
            trainer__pb2.RegisterPokemonRequest.SerializeToString,
            trainer__pb2.RegisterPokemonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Training(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trainer.TrainerService/Training',
            trainer__pb2.TrainingResults.SerializeToString,
            trainer__pb2.TrainingResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
