# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trainer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'trainer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrainer.proto\x12\x07trainer\":\n\x16RegisterPokemonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cnetwork_addr\x18\x02 \x01(\t\"G\n\x17RegisterPokemonResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\"9\n\x0fTrainingResults\x12\x12\n\npokemon_id\x18\x01 \x01(\t\x12\x12\n\ninput_data\x18\x02 \x01(\x0c\"*\n\x17TrainingResultsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xae\x01\n\x0eTrainerService\x12T\n\x0fRegisterPokemon\x12\x1f.trainer.RegisterPokemonRequest\x1a .trainer.RegisterPokemonResponse\x12\x46\n\x08Training\x12\x18.trainer.TrainingResults\x1a .trainer.TrainingResultsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trainer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERPOKEMONREQUEST']._serialized_start=26
  _globals['_REGISTERPOKEMONREQUEST']._serialized_end=84
  _globals['_REGISTERPOKEMONRESPONSE']._serialized_start=86
  _globals['_REGISTERPOKEMONRESPONSE']._serialized_end=157
  _globals['_TRAININGRESULTS']._serialized_start=159
  _globals['_TRAININGRESULTS']._serialized_end=216
  _globals['_TRAININGRESULTSRESPONSE']._serialized_start=218
  _globals['_TRAININGRESULTSRESPONSE']._serialized_end=260
  _globals['_TRAINERSERVICE']._serialized_start=263
  _globals['_TRAINERSERVICE']._serialized_end=437
# @@protoc_insertion_point(module_scope)
